environment:
  PYPI_USERNAME: ffalcinelli
  PYPI_PASSWORD:
    secure: hYfviymcELExtXhgCDbVTg==
  matrix:
    - python: 27
    - python: 27-x64
    - python: 34
    - python: 34-x64
    - python: 35
    - python: 35-x64
    - python: 36
    - python: 36-x64

install:
  - "SET PATH=C:\\Python%PYTHON%;c:\\Python%PYTHON%\\scripts;%PATH%"
  - "python -m pip install --disable-pip-version-check -U pip"
  - "pip install -e .[test]"

build: false

test_script:
  - py.test pydivert --capture=no -v --cov pydivert
  - python -u setup.py sdist bdist_wheel
  - codecov
  - ps: Get-ChildItem dist\*.whl | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

after_test:
  - pip install twine

on_success:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq "true"){ $ErrorActionPreference='silentlycontinue' ; twine upload -u $env:PYPI_USERNAME -p $env:PYPI_PASSWORD dist\* 2>$null ; echo "Twine upload done. Check on PyPI" } else { echo "Not a tagged commit. Skipping deployment on PyPI."}